eryuLab/SkillMaster

src/main/java/net/lifecity/mc/skillmaster/SkillCommand.kt

SkillCommandのエラーを修正しました
N/A
N/A

[fix]: SkillCommand.ktのエラーを修正

---

src/main/java/net/lifecity/mc/skillmaster/skill/skills/RazorStub.kt

[update]: ターゲットに5ダメージ与えるように

---

src/main/java/net/lifecity/mc/skillmaster/SkillCommand.kt
src/main/java/net/lifecity/mc/skillmaster/game/Game.kt

ユーザーの高さ制限を判定する部分で、returnしないようにした。
```kotlin
// ユーザーの高さ確認
for (team in teams) {
for (user in team.userArray) {
val userY = user.player.location.y
val stage = getNowStage()
stage?.let {
if (userY >= stage.highestHeight + HEIGHT_LIMIT) {
// 下方向に飛ばす
user.player.velocity.add(Vector(0.0, -2.75, 0.0))
}
}
}
}
```
N / A
- close #162

[バグ]: ゲームがスタートしないバグの修正

---

src/main/java/net/lifecity/mc/skillmaster/skill/skills/RazorStub.kt
src/main/java/net/lifecity/mc/skillmaster/utils/DrawParticle.kt
src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt

- スキルが有効範囲内であるか確かめる当たり判定のクラスを作成
- スキルのライトエフェクトを実装する方法をエフェクトクラスにまとめた
N / A
- close #165 
- close #166

エフェクトクラスの実装＆当たり判定クラスの実装

---

src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/Attack.kt
src/main/java/net/lifecity/mc/skillmaster/skill/separatedskills/EmptyForm.kt
src/main/java/net/lifecity/mc/skillmaster/skill/separatedskills/KaraNoKamae.kt
src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt

CompositeSkillとDefenseを継承、実装した  
N/A
- close #175

[新機能]: 直剣スキル「空の構え」の実装

---

src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/Attack.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/GiveBuff.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/Knockback.kt
src/main/java/net/lifecity/mc/skillmaster/skill/separatedskills/EmptyForm.kt
src/main/java/net/lifecity/mc/skillmaster/skill/separatedskills/KaraNoKamae.kt
src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt

- バフ専用のインターフェースを実装
- ノックバック専用のインターフェースを実装
スキルによる攻撃をするときはAttackまたはKnockbackを実装する  
Attackは攻撃対象にダメージとノックバックを同時に付与する  
Knockbackは攻撃対象にノックバックのみを付与する  
キックなどの攻撃力のないかつインターバルの短いスキルが攻撃力加算バフで強くなるのを防止するために分けました。  
- close #181

[品質向上]: スキルインターフェースの追加

---

src/main/java/net/lifecity/mc/skillmaster/EventListener.kt
src/main/java/net/lifecity/mc/skillmaster/SkillCommand.kt
src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/Attack.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/GiveBuff.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/Knockback.kt
src/main/java/net/lifecity/mc/skillmaster/skill/separatedskills/EmptyForm.kt
src/main/java/net/lifecity/mc/skillmaster/skill/separatedskills/KaraNoKamae.kt
src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt

メニュー棒を取得するコマンドの追加  
メニュー棒をクリックしたときにメニューが開かれる処理の追加
N/A
- close #180

[新機能]: メニュー棒システムの実装

---

src/main/java/net/lifecity/mc/skillmaster/SkillCommand.kt
src/main/java/net/lifecity/mc/skillmaster/exceptions.kt
src/main/java/net/lifecity/mc/skillmaster/game/Game.kt
src/main/java/net/lifecity/mc/skillmaster/game/GameList.kt
src/main/java/net/lifecity/mc/skillmaster/game/stage/GameStageList.kt
src/main/java/net/lifecity/mc/skillmaster/user/SkillUserList.kt

変更点
- StageNotFoundExceptionの追加
- GameNotFoundExceptionの追加
- SkillUserListのgetメソッドにoperator修飾子を追加
- SkillCommand内でNullチェックによってエラーチェックしてた箇所をtry-catchによるエラーチェックに変更
N / A
- close #144 
- close #187 
- close #182

Exceptionの追加＆operator修飾子の付与

---

src/main/java/net/lifecity/mc/skillmaster/game/Game.kt

BossBarを実装し、ゲームの残り時間を表示するようにしました
N/A
- close #146

[update]: ボスバーで残り時間を表示するようにした

---

src/main/java/net/lifecity/mc/skillmaster/EventListener.kt
src/main/java/net/lifecity/mc/skillmaster/SkillCommand.kt
src/main/java/net/lifecity/mc/skillmaster/SkillMaster.kt
src/main/java/net/lifecity/mc/skillmaster/utils/Logger.kt
src/main/java/net/lifecity/mc/skillmaster/utils/Messager.kt

- プレイヤーにメッセージを送信するMessagerクラスの追加
- コンソールにログを送信するLoggerクラスの追加
N / A
- close #189

Messagerクラスの追加&Loggerクラスの追加

---

src/main/java/net/lifecity/mc/skillmaster/utils/DrawParticle.kt

DrawParticleのメソッドにspeedを追加した
補足事項を記載
- close #193

[update]: 引数にspeedを追加

---

src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/SlapStep.kt

スキルの詳細を参照してください
N/A
- close #205

[add]: 直剣スキル「スラップステップ」の実装

---

docker/paper/Dockerfile
docker/paper/serverfiles/start-server.sh
docker/waterfall/Dockerfile
docker/waterfall/serverfiles/start-server.sh

タイトル通りです
補足事項を記載
- close #Issue番号

[fix]: start-server.shから改行をなくし、エラーを修正した

---

src/main/java/net/lifecity/mc/skillmaster/utils/DrawParticle.kt

円の周期2πを周期πにしたメソッドを追加することで、半円を実現させた。
補足事項を記載
- close #199

[update]: 半円を描画するメソッドの追加

---

src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/skills/Kick.kt

Knockbackインターフェースを使って対象をノックバックさせた
N/A
- close #201

[新スキル]: 「蹴り」の実装

---

src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/Attack.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/Knockback.kt
src/main/java/net/lifecity/mc/skillmaster/skill/testskills/JuRenGeki.kt

タイマーで2tickに1ダメ―ジ与える十連撃スキルを実装
N/A
- close #213

テストスキル「十連撃」を実装

---

src/main/java/net/lifecity/mc/skillmaster/skill/CompositeSkill.kt
src/main/java/net/lifecity/mc/skillmaster/skill/Skill.kt

スキル発動前に発動条件を確認した。
N/A
- close #211

[update]: スキルに発動条件を追加

---

src/main/java/net/lifecity/mc/skillmaster/skill/Skill.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/KaraNoKamae.kt
src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt

- モードシステムの書き方を変更
- スキル「空の構え」のバグ修正
- スキルに標準の発動条件を実装
issue書かなくてごめんなさい
補足事項を記載
なし

[結合]: 結合作業と簡単なバグを修正

---

src/main/java/net/lifecity/mc/skillmaster/skill/Skill.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/KaraNoKamae.kt
src/main/java/net/lifecity/mc/skillmaster/user/ModeManager.kt
src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt

- ModeManagerにモードプロパティとモード変更時の処理を持たせた
- ユーザーにmodeプロパティを持たせた
N/A
- close #116

[品質向上]: モードクラスの実装

---

src/main/java/net/lifecity/mc/skillmaster/skill/Skill.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/KaraNoKamae.kt
src/main/java/net/lifecity/mc/skillmaster/user/ModeManager.kt
src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt

inv.clear(index)からinv.setItem(index, ItemStack(Material.AIR))に変えた
N/A
- close #226

[バグ修正]: インベントリのアイテムを消去

---

src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt

[update]: 条件分岐をまとめた

---

src/main/java/net/lifecity/mc/skillmaster/skill/skills/Kick.kt
src/main/java/net/lifecity/mc/skillmaster/skill/skills/Thrust.kt

処理の位置を変えて攻撃が当たらなくてもSEとLEを強制表示させた。
N/A
- close #216

[品質向上]: エフェクトを強制表示

---

src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/SlapStep.kt

下方向にブロックがあるか判定するメソッドcheckBottom()を修正  
N/A
- close #234

[バグ修正]: スラップステップのバグを修正

---

src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt

[プレイヤー間の角度の求め方.pdf](https://github.com/eryuLab/SkillMaster/files/9972465/default.pdf)
N / A
- close #236

[update]:　２体のエンティティが立っている位置をつないだベクトルの角度を求めるメソッドの追加

---

src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt

具体的な実装方法または変更点を記載
補足事項を記載
- close #Issue番号

[fix]:　角度の値がおかしいバグの修正

---

src/main/java/net/lifecity/mc/skillmaster/skill/skills/RazorStub.kt
src/main/java/net/lifecity/mc/skillmaster/skill/skills/Thrust.kt

[品質向上]: スキル詳細を適用

---

src/main/java/net/lifecity/mc/skillmaster/EventListener.kt
src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/JumpAttackSlash.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/LeafFlow.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/Okigiri.kt
src/main/java/net/lifecity/mc/skillmaster/skill/skills/Kick.kt
src/main/java/net/lifecity/mc/skillmaster/utils/NearTargets.kt

[スキル詳細ページ](https://github.com/eryuLab/KoryuServerDocument/blob/main/%E6%B1%BA%E5%AE%9A%E4%BA%8B%E9%A0%85/%E3%82%B9%E3%82%AD%E3%83%AB/%E3%82%B9%E3%82%AD%E3%83%AB%E8%A9%B3%E7%B4%B0.md#%E7%BD%AE%E3%81%8D%E6%96%AC%E3%82%8A)に従って実装
N/A
- close #206

[新スキル]: 直剣「置き斬り」

---

docker/paper/serverfiles/start-server.sh
docker/waterfall/serverfiles/start-server.sh

set 構文でエラーが発生していたため修正しました
補足事項を記載
- close #Issue番号

[fix]:　Dockerのスクリプトのバグを修正

---

src/main/java/net/lifecity/mc/skillmaster/SkillCommand.kt

この提案によって改善される点
- コードのインデントが浅くなった
- SubCommandがわかりやすくなった
補足事項を記載
- close #Issue番号

[update]:　新たなコマンドシステムの提案

---

src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/skills/Kazagiri.kt

[新スキル]: 直剣「風斬り」

---

src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/IkkikaseiNoKamae.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/KaraNoKamae.kt
src/main/java/net/lifecity/mc/skillmaster/skill/compositeskills/NormalDefense.kt
src/main/java/net/lifecity/mc/skillmaster/skill/function/Defense.kt
src/main/java/net/lifecity/mc/skillmaster/utils/TargetSearch.kt

[新スキル]: 直剣「一気呵成の構え」

---

src/main/java/net/lifecity/mc/skillmaster/game/GameManager.kt

ボスバーからプレイヤーを削除する処理の位置を変えた
N/A
- close #248

[update]: ボスバー非表示化のタイミングをずらした

---

src/main/java/net/lifecity/mc/skillmaster/EventListener.kt
src/main/java/net/lifecity/mc/skillmaster/game/Game.kt
src/main/java/net/lifecity/mc/skillmaster/game/games/Duel.kt
src/main/java/net/lifecity/mc/skillmaster/game/games/Training.kt

イベントからゲームにアクセスした
N/A
- close #94

[品質向上]: ゲーム中の途中退出時の処理を追加

---

src/main/java/net/lifecity/mc/skillmaster/EventListener.kt
src/main/java/net/lifecity/mc/skillmaster/SkillMaster.kt
src/main/java/net/lifecity/mc/skillmaster/inventory/UserInventory.kt
src/main/java/net/lifecity/mc/skillmaster/skill/SkillManager.kt
src/main/java/net/lifecity/mc/skillmaster/user/SkillUser.kt
src/main/java/net/lifecity/mc/skillmaster/user/mode/ModeManager.kt
src/main/java/net/lifecity/mc/skillmaster/user/skillset/SkillButton.kt
src/main/java/net/lifecity/mc/skillmaster/user/skillset/SkillCard.kt
src/main/java/net/lifecity/mc/skillmaster/user/skillset/SkillKeySet.kt
src/main/java/net/lifecity/mc/skillmaster/user/skillset/SkillSet.kt
src/main/java/net/lifecity/mc/skillmaster/user/skillset/UserSkillSet.kt
src/main/java/net/lifecity/mc/skillmaster/utils/file/data/SkillSetConfig.kt
src/main/resources/data/skillset.yml

ymlファイルにスキルセットを保存してリログしてもスキル構成が保持される機能を作った
N/A
- close #256

[新機能]: スキルセットを保存するシステムを作成

---

src/main/java/net/lifecity/mc/skillmaster/EventListener.kt
src/main/java/net/lifecity/mc/skillmaster/game/GameManager.kt
src/main/java/net/lifecity/mc/skillmaster/user/UserEffect.kt

UserEffectクラスを作り、エフェクトを実装
N/A
- close #252

[品質向上]: プレイヤーのTP時と死亡時にエフェクトを追加
